Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2022-07-21 17:42:30,808 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2022-07-21 17:42:30,809 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2022-07-21 17:42:30,810 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2022-07-21 17:42:30,810 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;5;39m2022-07-21 17:42:30,811 :: INFO :: root :: sync_photos.py :: 41 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/photos ...[0m
[38;5;196m2022-07-21 17:42:30,811 :: ERROR :: root :: sync_photos.py :: 49 :: Failed to download /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/photos: __init__() missing 1 required positional argument: 'reason'[0m
