DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data
DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data
DEBUG    root:usage.py:102 Usage cache file not found, creating: /config/.data
DEBUG    root:usage.py:132 Atomically saved usage cache to: /config/.data
DEBUG    root:usage.py:271 Installing new instance
DEBUG    root:usage.py:215 Posting new installation to: None
DEBUG    root:usage.py:221 Successfully registered new installation: 80d73a07-4321-4218-a6ad-37a16deef134
DEBUG    root:usage.py:277 Installation completed with ID: 80d73a07-4321-4218-a6ad-37a16deef134
DEBUG    root:usage.py:295 Posting heartbeat to: None
ERROR    root:usage.py:189 Unexpected error during request: Error occurred.
ERROR    root:usage.py:303 Heartbeat failed: no response
DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data