DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data
DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data
DEBUG    root:usage.py:102 Usage cache file not found, creating: /config/.data
DEBUG    root:usage.py:132 Atomically saved usage cache to: /config/.data
DEBUG    root:usage.py:271 Installing new instance
DEBUG    root:usage.py:215 Posting new installation to: None
DEBUG    root:usage.py:221 Successfully registered new installation: a8412bee-8aea-49aa-9c45-47315bfc5822
DEBUG    root:usage.py:277 Installation completed with ID: a8412bee-8aea-49aa-9c45-47315bfc5822
DEBUG    root:config_logging.py:44 Checking root destination ...
DEBUG    root:usage.py:40 Initialized usage cache at: /config/.data