Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2022-07-22 16:04:34,366 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2022-07-22 16:04:34,367 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2022-07-22 16:04:34,367 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2022-07-22 16:04:34,368 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;21m2022-07-22 16:04:34,370 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file session_data/quentintarantinohotmailfr.session[0m
[38;5;39m2022-07-22 16:04:34,371 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2022-07-22 16:04:34,371 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2022-07-22 16:04:34,372 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;5;226m2022-07-22 16:04:34,372 :: WARNING :: root :: sync.py :: 75 :: Nothing to sync. Please add drive: and/or photos: section in config.yaml file.[0m
[38;5;39m2022-07-22 16:04:34,372 :: INFO :: root :: sync.py :: 127 :: Resyncing at Fri Jul 22 16:04:34 2022 ...[0m
