DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): api.telegram.org:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://api.telegram.org:443 "POST /botbot_token/sendMessage?chat_id=chat_id&text=Two-step+authentication+for+iCloud+Drive%2C+Photos+%28Docker%29+is+required.%0A++++++++++++++++Please+login+to+your+server+and+authenticate.+Please+run+-%0A++++++++++++++++%60docker+exec+-it+--user%3Dabc+icloud+%2Fbin%2Fsh+-c%0A++++++++++++++++%22icloud+--session-directory%3D%2Fconfig%2Fsession_data+--username%3Dusername%40icloud.com%22%60. HTTP/1.1" 404 55
ERROR    root:notify.py:46 Failed to send telegram notification. Response: {"ok":false,"error_code":404,"description":"Not Found"}
WARNING  root:config_parser.py:396 Warning: webhook_url is not found in app > discord > webhook_url.
WARNING  root:config_parser.py:408 Warning: username is not found in app > discord > username.
WARNING  root:notify.py:77 Not sending 2FA notification because Discord is not configured.
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): api.pushover.net:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://api.pushover.net:443 "POST /1/messages.json HTTP/1.1" 400 None
ERROR    root:notify.py:105 Failed to send Pushover notification. Response: {"token":"invalid","errors":["application token is invalid, see https://pushover.net/api"],"status":0,"request":"1c12699e-b8ed-441f-b9a6-0c126a590e4d"}
WARNING  root:config_parser.py:196 Warning: no_tls is not found in app > smtp > no_tls
ERROR    root:notify.py:155 Failed to send email: .