Loading config from /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/data/test_config.yaml ...
[38;21m2023-12-01 18:24:19,654 :: DEBUG :: icloudpy.base :: base.py :: 246 :: Using session file /tmp/icloudpy/runner/quentintarantinohotmailfr.session[0m
[38;5;39m2023-12-01 18:24:19,654 :: INFO :: icloudpy.base :: base.py :: 253 :: Session file does not exist[0m
[38;21m2023-12-01 18:24:19,655 :: DEBUG :: icloudpy.base :: base.py :: 318 :: Authenticating as quentintarantino@hotmail.fr[0m
[38;21m2023-12-01 18:24:19,655 :: DEBUG :: icloudpy.base :: base.py :: 350 :: Authentication completed successfully[0m
[38;5;39m2023-12-01 18:24:19,656 :: INFO :: root :: sync_drive.py :: 193 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;21m2023-12-01 18:24:19,657 :: DEBUG :: root :: sync_drive.py :: 136 :: No changes detected. Skipping the file /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
[38;21m2023-12-01 18:24:19,658 :: DEBUG :: root :: sync_drive.py :: 139 :: Changes detected: local_modified_time is 1701455059, remote_modified_time is 1588464917, local_file_size is 340532 and remote_file_size is 197334.[0m
[38;5;39m2023-12-01 18:24:19,658 :: INFO :: root :: sync_drive.py :: 193 :: Downloading /home/runner/work/icloud-drive-docker/icloud-drive-docker/tests/temp/icloud/drive/Scanned document 1.pdf ...[0m
